name: CI/CD Pipeline

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write  

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: rizkyrs10  

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ env.IMAGE_OWNER }} --password-stdin

    - name: Build and push Go service image
      run: |
        docker build -t $REGISTRY/$IMAGE_OWNER/go-service:latest ./go-service
        docker push $REGISTRY/$IMAGE_OWNER/go-service:latest

    - name: Build and push Node.js service image
      run: |
        docker build -t $REGISTRY/$IMAGE_OWNER/node-service:latest ./node-service
        docker push $REGISTRY/$IMAGE_OWNER/node-service:latest

    - name: Upload Kubernetes manifests
      uses: actions/upload-artifact@v3
      with:
        name: k8s-manifests
        path: k8s/
